language: objective-c
os: osx
osx_image: xcode9

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=SwipeTransition.xcodeproj
    - CONFIG=Release
    - ACTION="build-for-testing test-without-building"

branches:
  only: 
    - master

cache:
  directories:
    - Carthage

matrix:
  include:
    - env: JOB=pod_lint
      script:
        - pod lib lint --quick

    - env: JOB=xcode SCHEME=Replacer XCODE_OPTION="-sdk iphonesimulator -destination \"name=iPhone 8\""

script:
  - set -o pipefail
  - xcodebuild $ACTION -project "$PROJECT" -scheme "$SCHEME" $XCODE_OPTION -configuration "$CONFIG" ENABLE_TESTABILITY=YES | xcpretty

notifications:
  email: false
